import assets from "./assets";

const NFTData = [
  {
    id: "NFT-01",
    name: "Hepsi Burada",
    creator: "D-MARKET Elektronik",
    taninmis:"1 Tanınmış",
    marka:"465 Marka",
    price: 4.25,
    description:
      "D-Market Elektronik (hepsiburada.com) adına TÜRKPATENT siciline kayıtlı 1'i tanınmış marka olmak üzere 465 adet marka/marka başvurusu bulunmaktadır.",
    image: assets.hepsiburada,
    bids: [
      {
        id: "BID-11",
        image: assets.hb1,
        detayimg: assets.hbmd1,
        markaadi: "hepsiburada.com ",
        basvuruno: "T/02598",
        kisadurum: "Kabul Edildi",
        basvurutarihi:"24.12.2014",
        bultentarihi:"-",
        sinif:"99",
        durum:"'hepsiburada.com + şekil' için 24.12.2014 tarihinde tanınmış marka başvurusu yapılmış ve Kurum tarafından bu başvuru 12.05.2016 tarihinde kabul edilerek sicile kaydedilmiştir.",
       
      },
      {
        id: "BID-12",
        image: assets.hb2,
        detayimg: assets.hbmd2,
        markaadi: "hepsiburada dolu dolu kahvaltı ",
        basvuruno: "2023/003124",
        kisadurum: "Yayın Kararı",
        basvurutarihi:"09.01.2023",
        bultentarihi:"13.02.2023",
        sinif:"29 / 35 / 38 / 43",
        durum:"Marka başvurusu 414. marka bülteninde, 13.02.2023 tarihinde yayınlanmıştır. Üçüncü şahıs itiraz süresi 2 ay olup 13.04.2023 tarihine kadar bir itiraz gelmemesi durumunda bu tarihten sonra tescil kararı beklenecektir.",
      },
      {
        id: "BID-13",
        image: assets.hb3,
        detayimg: assets.hbmd3,
        markaadi: "dolu dolu kahvaltı ",
        basvuruno: "2023/003118",
        kisadurum: "Yayın Kararı",
        basvurutarihi:"09.01.2023",
        bultentarihi:"13.02.2023",
        sinif:"29 / 35 / 38 / 43",
        durum:"Marka başvurusu 414. marka bülteninde, 13.02.2023 tarihinde yayınlanmıştır. Üçüncü şahıs itiraz süresi 2 ay olup 13.04.2023 tarihine kadar bir itiraz gelmemesi durumunda bu tarihten sonra tescil kararı beklenecektir.",
      },
      {
        id: "BID-14",
        image: assets.hb4,
        detayimg: assets.hbmd4,
        markaadi: "hepsiburada okul alışverişi burada başlar",
        basvuruno: "2023/001097",
        kisadurum: "Yayın Kararı",
        basvurutarihi:"04.01.2023",
        bultentarihi:"13.02.2023",
        sinif:"16 / 35 / 38 / 41",
        durum:"Marka başvurusu 414. marka bülteninde, 13.02.2023 tarihinde yayınlanmıştır. Üçüncü şahıs itiraz süresi 2 ay olup 13.04.2023 tarihine kadar bir itiraz gelmemesi durumunda bu tarihten sonra tescil kararı beklenecektir.",
      },
      {
        id: "BID-15",
        image: assets.hb5,
        detayimg: assets.hbmd5,
        markaadi: "hepsiburada pazarlama çözümleri",
        basvuruno: "2022/209138",
        kisadurum: "Yayın Kararı",
        basvurutarihi:"29.12.2022",
        bultentarihi:"27.01.2023",
        sinif:"35",
        durum:"Marka başvurusu 413. marka bülteninde, 27.01.2023 tarihinde yayınlanmıştır. Üçüncü şahıs itiraz süresi 2 ay olup 27.03.2023 tarihine kadar bir itiraz gelmemesi durumunda bu tarihten sonra tescil kararı beklenecektir.",
      },
      {
        id: "BID-16",
        image: assets.hb6,
        detayimg: assets.hbmd6,
        markaadi: "hepsiburada reboxing",
        basvuruno: "2022/195814",
        kisadurum: "Yayın Kararı",
        basvurutarihi:"15.12.2022",
        bultentarihi:"12.01.2023",
        sinif:"16",
        durum:"Marka başvurusu 412. marka bülteninde, 12.01.2023 tarihinde yayınlanmıştır. Üçüncü şahıs itiraz süresi 2 ay olup 12.03.2023 tarihine kadar bir itiraz gelmemesi durumunda bu tarihten sonra tescil kararı beklenecektir.",
      },
      {
        id: "BID-17",
        image: assets.hb7,
        detayimg: assets.hbmd7,
        markaadi: "hepsiburada reboxing",
        basvuruno: "2022/195810",
        kisadurum: "Yayın Kararı",
        basvurutarihi:"29.12.2022",
        bultentarihi:"27.01.2023",
        sinif:"35",
        durum:"Marka başvurusu 412. marka bülteninde, 12.01.2023 tarihinde yayınlanmıştır. Üçüncü şahıs itiraz süresi 2 ay olup 12.03.2023 tarihine kadar bir itiraz gelmemesi durumunda bu tarihten sonra tescil kararı beklenecektir.",
      },
      {
        id: "BID-18",
        image: assets.hb8,
        detayimg: assets.hbmd8,
        markaadi: "reboxing",
        basvuruno: "2022/195806",
        kisadurum: "Yayın Kararı",
        basvurutarihi:"15.12.2022",
        bultentarihi:"12.01.2023",
        sinif:"16",
        durum:"Marka başvurusu 412. marka bülteninde, 12.01.2023 tarihinde yayınlanmıştır. Üçüncü şahıs itiraz süresi 2 ay olup 12.03.2023 tarihine kadar bir itiraz gelmemesi durumunda bu tarihten sonra tescil kararı beklenecektir.",
      },
      {
        id: "BID-19",
        image: assets.hb9,
        detayimg: assets.hbmd9,
        markaadi: "hepsiburada işte arkadaşım",
        basvuruno: "2022/188883",
        kisadurum: "Yayın Kararı",
        basvurutarihi:"07.12.2022",
        bultentarihi:"27.12.2022",
        sinif:"09 / 35 / 42",
        durum:"Marka başvurusu 411. marka bülteninde, 27.12.2023 tarihinde yayınlanmıştır. Üçüncü şahıs itiraz süresi 2 ay olup 27.02.2023 tarihine kadar bir itiraz gelmemesi durumunda bu tarihten sonra tescil kararı beklenecektir.",
      },
      {
        id: "BID-110",
        image: assets.hb10,
        detayimg: assets.hbmd10,
        markaadi: "leif hepsiburada",
        basvuruno: "Başvuru No : 2022/180836",
        kisadurum: "Yayın Kararı",
        basvurutarihi:"25.11.2022",
        bultentarihi:"27.01.2023",
        sinif:"03 / 14 / 18",
        durum:"Marka başvurusu 414. marka bülteninde, 13.02.2023 tarihinde yayınlanmıştır. Üçüncü şahıs itiraz süresi 2 ay olup 32.04.2023 tarihine kadar bir itiraz gelmemesi durumunda bu tarihten sonra tescil kararı beklenecektir.",
    
        
       
      },
    ],
  },
  {
    id: "NFT-02",
    name: "Trendyol",
    creator: "DSM GRUP Danışmanlık",
    taninmis:"2 Tanınmış",
    marka:"190 Marka",
    price: 7.25,
    description:
      "Firmanın 1 i tanınmış marka olmak üzere TÜRKPATENT siciline kayıtlı 190 adet markası/marka başvurusu bulunmaktadır.",
    image: assets.trend1,
    bids: [
      {
        id: "BID-21",
        image: assets.ty1,
        detayimg: assets.tymd1,
        markaadi: "trendyolmilla",
        basvuruno: "T/03611",
        kisadurum: "Reddedildi",
        basvurutarihi:"11.08.2021",
        bultentarihi:"-",
        sinif:"-",
        durum:"Tanınmış marka siciline kayıt edilmek istenen trendyolmilla ibaresi için 11.08.2021 tarihinde başvuru yapılmış olup, 10.02.2023 tarihinde söz konusu başvuru TÜRKPATENT tarafından reddedilmiştir.",
      },
     
      {
        id: "BID-22",
        image: assets.ty2,
        detayimg: assets.tymd2,
        markaadi: "trendyol",
        basvuruno: "T/02568",
        kisadurum: "Kabul Edildi",
        basvurutarihi:"12.01.2015",
        bultentarihi:"-",
        sinif:"99 / *",
        durum:"trendyol ibaresi TÜRKPATENT tarafından tanınmış marka siciline kaydedilmiştir.",
      },
      {
        id: "BID-23",
        image: assets.ty3,
        detayimg: assets.tymd3,
        markaadi: "yarının köyleri",
        basvuruno: "2022/163795",
        kisadurum: "Tescil ücreti bildirim yazısı.",
        basvurutarihi:"31.10.2022",
        bultentarihi:"14.11.2022",
        sinif:"35 / 41 / 42 / 44",
        durum:"Marka başvurusunun tescil ile sonuçlanmasına karar verilmiş ve tescil ücreti bildirimi 24.01.2023 tarihinde tebliğ edilmiştir. Tescil ücretinin 2 ay içinde yatırılması durumunda marka tescil edilecektir.",
      },
      {
        id: "BID-24",
        image: assets.ty4,
        detayimg: assets.tymd4,
        markaadi: "trendyol yarının köyleri",
        basvuruno: "2022/163794",
        kisadurum: "Yayınlandı",
        basvurutarihi:"31.10.2022",
        bultentarihi:"27.09.2022",
        sinif:"35 / 41 / 42 / 44",
        durum:"Marka başvurusu 410. marka bülteninde 12.12.2022 de yayınlanmış olup yayın süresi içinde bir itiraz kaydı bulunmamaktadır. Başvuru sahibine tescil kararının tebliğ edilmesi beklenmektedir.",
      },
      {
        id: "BID-25",
        image: assets.ty5,
        detayimg: assets.tymd5,
        markaadi: "trendyol geleceğin köyleri",
        basvuruno: "2022/132533",
        kisadurum: "Tescil Edildi",
        basvurutarihi:"12.09.2022",
        bultentarihi:"-",
        sinif:"35 / 41 / 42 / 44",
        durum:"Marka, başvurulduğu tüm sınıflarda 30.01.2023 tarihinde tescil edilmiştir.",
      },
      {
        id: "BID-26",
        image: assets.ty6,
        detayimg: assets.tymd6,
        markaadi: "trendyol dijital köyler",
        basvuruno: "2022/132532",
        kisadurum: "Tescil ücreti bildirim yazısı",
        basvurutarihi:"12.09.2022",
        bultentarihi:"14.11.2022",
        sinif:"35 / 41 / 42 / 44",
        durum:"Marka başvurusunun tescil ile sonuçlanmasına karar verilmiş ve tescil ücreti bildirimi 23.01.2023 tarihinde tebliğ edilmiştir. Tescil ücretinin 2 ay içinde yatırılması durumunda marka tescil edilecektir.",
      },
      {
        id: "BID-27",
        image: assets.ty7,
        detayimg: assets.tymd7,
        markaadi: "trendyol care collectıon",
        basvuruno: "2022/108935",
        kisadurum: "Tescil Edildi.",
        basvurutarihi:"02.08.2022",
        bultentarihi:"29.08.2022",
        sinif:"25 / 35",
        durum:"Marka, başvurulduğu tüm sınıflarda 21.12.2022 tarihinde tescil edilmiştir.",
      },
      {
        id: "BID-28",
        image: assets.ty8,
        detayimg: assets.tymd8,
        markaadi: "tygmarket",
        basvuruno: "2022/075897",
        kisadurum: "Tescil Edildi",
        basvurutarihi:"27.05.2022",
        bultentarihi:"27.06.2022",
        sinif:"01 / 02 / 03 / 04 / 05 / 06 / 07 / 08 / 09 / 10 / 11 / 12 / 13 / 14 / 15 / 16 / 17 / 18 / 19 / 20 / 21 / 22 / 23 / 24 / 25 / 26 / 27 / 28 / 29 / 30 / 31 / 32 / 33 / 34 / 35 / 36 / 37 / 38 / 39 / 40 / 41 / 42 / 43 / 44 / 45 ",
        durum:"Marka, başvurulduğu tüm sınıflarda 06.10.2022 tarihinde tescil edilmiştir.",
      },
      {
        id: "BID-29",
        image: assets.ty9,
        detayimg: assets.tymd9,
        markaadi: "trendyol akademi",
        basvuruno: "2022/073632",
        kisadurum: "Tescil Edildi",
        basvurutarihi:"24.05.2022",
        bultentarihi:"13.06.2022",
        sinif:"35 / 41 ",
        durum:"Marka, başvurulduğu tüm sınıflarda 30.09.2022 tarihinde tescil edilmiştir.",
      },
      {
        id: "BID-210",
        image: assets.ty10,
        detayimg: assets.tymd10,
        markaadi: "trendyol satıcı bilgi merkezi",
        basvuruno: "2022/073631",
        kisadurum: "Tescil Edildi",
        basvurutarihi:"24.05.2022",
        bultentarihi:"27.06.2022",
        sinif:"35 / 41",
        durum:"Marka, başvurulduğu tüm sınıflarda 04.10.2022 tarihinde tescil edilmiştir.",
      },
    ],
  },



  {
    id: "NFT-03",
    name: "n11.com ",
    creator: "DOĞUŞ PLANET Elektronik",
    taninmis:"1 Tanınmış",
    marka:"100 Marka",
    price: 95.25,
    description:
      "Firmanın 1 i tanınmış marka olmak üzere TÜRKPATENT siciline kayıtlı 100 adet markası/marka başvurusu bulunmaktadır.",
    image: assets.n11logo,
    bids: [
      {
        id: "BID-31",
        image: assets.n1,
        detayimg: assets.nmd1,
        markaadi: "n11.com",
        basvuruno: "T/02763",
        kisadurum: "Kabul edildi",
        basvurutarihi:"30.09.2015",
        bultentarihi:"-",
        sinif:"99 / *",
        durum:"n11.com ibaresi TÜRKPATENT tarafından tanınmış marka siciline kaydedilmiştir.",
      },
      {
        id: "BID-32",
        image: assets.n2,
        detayimg: assets.nmd2,
        markaadi: "11 n11 çabuk",
        basvuruno: "2022/136052",
        kisadurum: "Tescil edildi",
        basvurutarihi:"16.09.2022",
        bultentarihi:"12.10.2022",
        sinif:"09 / 16 / 35 / 36 / 38 / 39 / 41 / 42",
        durum:"Marka, başvurulduğu tüm sınıflarda 04.01.2023 tarihinde tescil edilmiştir.",
      },

      {
        id: "BID-33",
        image: assets.n3,
        detayimg: assets.nmd3,
        markaadi: "11 şekil",
        basvuruno: "2022/062435",
        kisadurum: "Tescil edildi",
        basvurutarihi:"29.04.2022",
        bultentarihi:"13.07.2022",
        sinif:"09 / 16 / 35 / 36 / 38 / 39 / 41 / 42",
        durum:"Marka, başvurulduğu tüm sınıflarda 28.11.2022 tarihinde tescil edilmiştir.",
      },
      {
        id: "BID-34",
        image: assets.n4,
        detayimg: assets.nmd4,
        markaadi: "n11 şekil",
        basvuruno: "2022/062434",
        kisadurum: "Red kararı itiraz",
        basvurutarihi:"29.04.2022",
        bultentarihi:"13.06.2022",
        sinif:"09 / 16 / 35 / 36 / 38 / 39 / 41 / 42",
        durum:"Marka başvurusu kısmi yayınlanmış (5/1(ç)), başvuru sahibi tarafından karar itiraz edilmiş ve bu itirazı da Kurum reddetmiştir. Kurumun mevcut ürün ve hizmetler bakımından tescil kararı vermesi beklenmekte olup başvuru süreci devam etmektedir.",
      },

      {
        id: "BID-35",
        image: assets.n5,
        detayimg: assets.nmd5,
        markaadi: "11 şekil",
        basvuruno: "2022/062432",
        kisadurum: "Tescil edildi",
        basvurutarihi:"29.04.2022",
        bultentarihi:"12.08.2022",
        sinif:"09 / 16 / 35 / 36 / 38 / 39 / 41 / 42",
        durum:"Marka, başvurulduğu tüm sınıflarda 25.12.2022 tarihinde tescil edilmiştir.",
      },

      {
        id: "BID-36",
        image: assets.n6,
        detayimg: assets.nmd6,
        markaadi: "n11depom e-ticaret lojistiği",
        basvuruno: "2021/051482",
        kisadurum: "Tescil edildi",
        basvurutarihi:"30.03.2021",
        bultentarihi:"14.06.2021",
        sinif:"35 / 39",
        durum:"Marka, başvurulduğu tüm sınıflarda 15.10.2021 tarihinde tescil edilmiştir.",
      },
      {
        id: "BID-37",
        image: assets.n7,
        detayimg: assets.nmd7,
        markaadi: "n11depom",
        basvuruno: "2021/048904",
        kisadurum: "Tescil edildi",
        basvurutarihi:"25.03.2021",
        bultentarihi:"14.06.2021",
        sinif:"35 / 39",
        durum:"Marka, başvurulduğu tüm sınıflarda 14.10.2021 tarihinde tescil edilmiştir.",
      },
      {
        id: "BID-38",
        image: assets.n8,
        detayimg: assets.nmd8,
        markaadi: "pet11",
        basvuruno: "2021/041286",
        kisadurum: "Tescil edildi",
        basvurutarihi:"12.03.2021",
        bultentarihi:"12.07.2021",
        sinif:"35",
        durum:"Marka, başvurulduğu tüm sınıfta 09.11.2021 tarihinde tescil edilmiştir.",
      },
      {
        id: "BID-39",
        image: assets.n9,
        detayimg: assets.nmd9,
        markaadi: "garaj11",
        basvuruno: "2021/041286",
        kisadurum: "Tescil edildi",
        basvurutarihi:"19.02.2021",
        bultentarihi:"17.05.2021",
        sinif:"03 / 09 / 12 / 14 / 16 / 18 / 24 / 25 / 26 / 28 / 29 / 30 / 31 / 32 / 33 / 34 / 35 / 36 / 37 / 39 / 41 / 42 / 43 ",
        durum:"Marka, başvurulduğu tüm sınıflarda 13.09.2022 tarihinde tescil edilmiştir.",
      },
      {
        id: "BID-310",
        image: assets.n10,
        detayimg: assets.nmd10,
        markaadi: "garaj11 güvenle al güvenle sat",
        basvuruno: "2021/027101",
        kisadurum: "Tescil edildi",
        basvurutarihi:"19.02.2021",
        bultentarihi:"27.04.2021",
        sinif:"03 / 09 / 12 / 14 / 16 / 18 / 24 / 25 / 26 / 28 / 29 / 30 / 31 / 32 / 33 / 34 / 35 / 36 / 37 / 39 / 41 / 42",
        durum:"Marka, başvurulduğu tüm sınıflarda 25.09.2022 tarihinde tescil edilmiştir.",
      },
    ],
  },
  // {
  //   id: "NFT-04",
  //   name: "Nifty NFT",
  //   creator: "Putri Intan",
  //   price: 54.25,
  //   description:
  //     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur.",
  //   image: assets.nft04,
  //   bids: [
  //     {
  //       id: "BID-41",
  //       name: "Jessica Tan",
  //       price: 56.25,
  //       image: assets.person02,
  //       date: "December 12, 2019 at 12:10 PM",
  //     },
  //     {
  //       id: "BID-42",
  //       name: "Jennifer Sia",
  //       price: 54.25,
  //       image: assets.person03,
  //       date: "December 27, 2019 at 1:50 PM",
  //     },
  //     {
  //       id: "BID-43",
  //       name: "Rosie Wong",
  //       price: 55.15,
  //       image: assets.person04,
  //       date: "December 31, 2019 at 3:50 PM",
  //     },
  //     {
  //       id: "BID-44",
  //       name: "Vincent Swift",
  //       price: 54.15,
  //       image: assets.person02,
  //       date: "December 31, 2019 at 3:50 PM",
  //     },
  //   ],
  // },
  // {
  //   id: "NFT-05",
  //   name: "Colorful circles",
  //   creator: "David doe",
  //   price: 10.25,
  //   description:
  //     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
  //   image: assets.nft05,
  //   bids: [
  //     {
  //       id: "BID-51",
  //       name: "Jessica Tan",
  //       price: 10.25,
  //       image: assets.person02,
  //       date: "December 12, 2019 at 12:10 PM",
  //     },
  //   ],
  // },
  // {
  //   id: "NFT-06",
  //   name: "Black box model",
  //   creator: "Leo Messi",
  //   price: 20.25,
  //   description:
  //     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
  //   image: assets.nft06,
  //   bids: [
  //     {
  //       id: "BID-61",
  //       name: "Jessica Tan",
  //       price: 20.25,
  //       image: assets.person02,
  //       date: "December 12, 2019 at 12:10 PM",
  //     },
  //     {
  //       id: "BID-62",
  //       name: "Jennifer Sia",
  //       price: 20.5,
  //       image: assets.person03,
  //       date: "December 27, 2019 at 1:50 PM",
  //     },
  //     {
  //       id: "BID-63",
  //       name: "Rosie Wong",
  //       price: 20.75,
  //       image: assets.person04,
  //       date: "December 31, 2019 at 3:50 PM",
  //     },
  //     {
  //       id: "BID-64",
  //       name: "Siti Nurhaliza",
  //       price: 21.25,
  //       image: assets.person02,
  //       date: "December 31, 2019 at 3:50 PM",
  //     },
  //     {
  //       id: "BID-65",
  //       name: "Kaitlyn Lee",
  //       price: 7.25,
  //       image: assets.person02,
  //       date: "December 31, 2019 at 3:50 PM",
  //     },
  //   ],
  // },
  // {
  //   id: "NFT-07",
  //   name: "Abstracto soulful art",
  //   creator: "Victor de la Cruz",
  //   price: 18.25,
  //   description:
  //     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Ullamcorper platea penatibus ornare egestas nulla ligula hendrerit nisl suscipit sociosqu maximus, tincidunt aptent habitant purus pharetra ultrices dapibus laoreet nisi lacinia. Porta malesuada netus vel sapien conubia porttitor aliquam ut pretium ante litora molestie senectus magna egestas sociosqu, eget aliquet fames pharetra felis posuere varius fringilla quisque in arcu montes eu ullamcorper.",
  //   image: assets.nft07,
  //   bids: [],
  // },
];

export { NFTData };
